# 参数要求： 写了可以不用，但是用了就一定不能错
run_id: qwenact
run_root_dir: results/Checkpoints
seed: 42
trackers: [jsonl, wandb]
wandb_entity: jinhuiye
wandb_project: llavavla
is_debug: false


framework:
  framework_py: DinoQFormerACT # 之后注意改名字，这里确保还能 loader 之前的ckpt --> 算了直接往最后版本去？
  qwenvl: # TODO 后期不能交qwenvl 应该直接vlm
    base_vlm: /mnt/petrelfs/yejinhui/Projects/llavavla/playground/Pretrained_models/Qwen2.5-VL-3B-Instruct
    attn_implementation: flash_attention_2
    vl_hidden_dim: 2048 # TODO 应该是要去读取 内部的config
  dino:
    dino_backbone: dinov2_vits14
  layer_qformer: 
    qformer_end_layer: 37
    qformer_start_layer: 36
    num_query_tokens: 64
    grad_scale: 0.5 # 让梯度经过这个模块的时候进行衰减，避免破坏VLM， # 似乎会影响学习
  action_model:
    action_model_type: DiT-B
    action_hidden_dim: 768
    action_dim: 7
    use_ema: false
    future_action_window_size: 15
    past_action_window_size: 0
    repeated_diffusion_steps: 8
  
  # waiting to check
  reduce_in_full_precision: true


datasets:
  vlm_data:
    dataset_py: vlm_datasets
    dataformat: llava_json
    dataset_use: asv2_conversation_en,asv2_detailed_description_en,asv2_region_captioning_en,coco_internvl_longcap_en,coco_karpathy_train_567_en,coco_negative_gpt4o_en,coco_poetry_zh,coco_rem_en_zh,cocorem_exist_yorn_en,cocotextv2_en,cocotextv2_gpt4o_en,okvqa_en,refcoco_grounding_aug_en,refcoco_grounding_en,tallyqa_coco_en,toloka_grounding_aug_en,vqav2_en,vsr_en
    eval_dataset: aokvqa_cauldron_llava_format
    data_flatten: false
    base_interval: 2
    max_pixels: 50176
    min_pixels: 784
    fix_image_size: [224, 224]
    model_max_length: 1024 # 似乎这里必须是4096， 有些相互关联的内容并没有处理到
    model_type: qwen2.5vl
    per_device_batch_size: 4

  vla_data:
    dataset_py: lerobot_datasets
    data_root_dir: /mnt/petrelfs/share/yejinhui/Datasets/OXE_LEROBOT
    data_mix: bridge_rt_1 # bridge_rt_1
    action_type: delta_ee # 这个没有生效
    CoT_prompt: "Your task is {instruction}. To identify the key objects for your task. Locate their bounding boxes in [x1,y1,x2,y2] format."
    CoT_answer: bbox # 这个可以design一下， 要模仿groot modility 中去定义
    default_image_resolution: [3, 224, 224] # 还没有生效
    per_device_batch_size: 16
    load_all_data_for_training: true # 考虑如何启用 eval set
    obs: ["image_0"] # 也还没有生效

trainer:
  epochs: 100 # 决定是否使用， 他和 max_train_steps 冲突
  max_train_steps: 100000
  num_warmup_steps: 5000
  save_interval: 5000
  eval_interval: 1000
  learning_rate:
    base: 5e-05
    qwen_vl_interface: 1.0e-05 # 整个freeze 掉了的时候会导致优化器 null error
    action_model: 1.0e-04
  lr_scheduler_type: cosine_with_min_lr
  scheduler_specific_kwargs:
    min_lr: 5.0e-07
  freeze_modules: ''
  loss_scale:
    vla: 1.0
    vlm: 0.1
  # pretrained_checkpoint: /mnt/petrelfs/yejinhui/Projects/llavavla/results/Checkpoints/1_need/0601_qwenact_fixqwen_32gpus_lr_1e-3_qformer_36_37/steps_100000/pytorch_model.pt
  # reload_modules: 'action_model,layer_qformer' # 警告： 这个可能会导致 模型无法收敛
  max_grad_norm: 1.0
  warmup_ratio: 0.1
  weight_decay: 0.0
  logging_frequency: 10
  gradient_clipping: 1.0
  gradient_accumulation_steps: 1

  optimizer:
    name: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-08
    weight_decay: 1.0e-08

  # 待确定的参数
  is_resume: false
  resume_epoch: null
  resume_step: null
  enable_gradient_checkpointing: true
  enable_mixed_precision_training: true
