action_dim: 7
action_model_type: DiT-B
data_root_dir: playground/Datasets/OXE_openvla
future_action_window_size: 15
logging_frequency: 10
gradient_clipping: 1.0
hf_token: HF_TOKEN
image_aug: true
is_debug: false
is_resume: false
load_all_data_for_training: true
past_action_window_size: 0
pretrained_checkpoint: null
repeated_diffusion_steps: 8
resume_epoch: null
resume_step: null
run_id: 0606_ftqwen_withoutprompt_bridge_rt_1_32gpus_lr_5e-5_qformer_36_37_rp
run_id_note: null
run_root_dir: results/Checkpoints
save_interval: 5000
seed: 42
trackers:
- jsonl
- wandb
use_ema: false
vla:
  base_vlm: /mnt/petrelfs/yejinhui/Projects/llavavla/playground/Pretrained_models/Qwen2.5-VL-3B-Instruct
  data_mix: bridge_rt_1
  enable_gradient_checkpointing: true
  enable_mixed_precision_training: true
  epochs: 100
  expected_world_size: 32
  freeze_llm_backbone: false
  freeze_modules: ''
  freeze_vision_backbone: false
  global_batch_size: 512
  learning_rate: 5.0e-05
  lr_scheduler_type: constant
  max_grad_norm: 1.0
  max_steps: 100000
  per_device_batch_size: 16
  qformer_end_layer: 37
  qformer_start_layer: 36
  reduce_in_full_precision: true
  shuffle_buffer_size: 250000
  train_strategy: fsdp-full-shard
  type: prism-dinosiglip-224px+oxe+diffusion
  unfreeze_last_llm_layer: false
  vla_id: prism-dinosiglip-224px+oxe+diffusion
  warmup_ratio: 0.0
  weight_decay: 0.0
  qwevl:
    attn_implementation: flash_attention_2

wandb_entity: jinhuiye
wandb_project: llavavla

vlm_data:
  dataset_use: sharegpt4v_coco
  eval_dataset: aokvqa_cauldron_llava_format
  video_max_frames: 8
  video_min_frames: 4
  data_flatten: false
  base_interval: 2
  max_pixels: 50176
  min_pixels: 784
  video_max_frame: 8
  video_min_frame: 4
  video_max_frame_pixels: 25088
  video_min_frame_pixels: 3136
  model_max_length: 4096
  model_type: qwen2.5vl
  per_device_batch_size: 4
