compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  deepspeed_config_file: scripts/run_scripts/ds_config.yaml
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_config:
  dynamo_backend: NVPRIMS_NVFUSER
  dynamo_mode: default
  dynamo_use_dynamic: true
  dynamo_use_fullgraph: true
enable_cpu_affinity: false
machine_rank: 0
main_process_ip: 'YES'
main_process_port: 2045
main_training_function: main
num_machines: 4
num_processes: 32
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
