# 参数要求： 写了可以不用，但是用了就一定不能错
run_id: starvla
run_root_dir: results/Checkpoints
seed: 42
trackers: [jsonl, wandb]
wandb_entity: jinhuiye
wandb_project: llavavla
is_debug: false


framework:
  framework_py: InternVLA-M1 # #  qwenpi | DinoQFormerACT
  qwenvl: # TODO 后期不能交qwenvl 应该直接vlm
    base_vlm: ./playground/Pretrained_models/Qwen2.5-VL-3B-Instruct
    attn_implementation: flash_attention_2
    vl_hidden_dim: 2048 # TODO 应该是要去读取 内部的config
  dino:
    dino_backbone: dinov2_vits14
  layer_qformer: 
    qformer_end_layer: 37
    qformer_start_layer: 36
    num_query_tokens: 64
    grad_scale: 0.5 # 让梯度经过这个模块的时候进行衰减，避免破坏VLM， # 似乎会影响学习
  action_model:
    action_model_type: DiT-B
    action_hidden_dim: 768
    action_dim: 7
    use_ema: false
    future_action_window_size: 15 # action chunk  ==  future + 1 TODO 这里需要换个说法
    past_action_window_size: 0
    repeated_diffusion_steps: 8
  
  fm_head_config:
    input_embedding_dim: 1536     # Action embedding 后的维度 48 * 32，和 DiT 的 attention_head_dim * attention_heads 对应，用于 ActionEncoder
    hidden_size: 1024     # 和 DiT 最后的 projection 对应，用于 ActionDecoder
    add_pos_embed: True
    max_seq_len: 1024
    action_dim: 7
    future_action_window_size: 15
    action_horizon: 16
    past_action_window_size: 0
    noise_beta_alpha: 1.5
    noise_beta_beta: 1.0
    noise_s: 0.999
    num_timestep_buckets: 1000
    num_inference_timesteps: 4
    num_target_vision_tokens: 32
    diffusion_model_cfg:    # DiT Transformers 的参数
      attention_head_dim: 48
      cross_attention_dim: 2048 # VLM 的 dim
      dropout: 0.2
      final_dropout: true
      interleave_self_attention: true
      norm_type: "ada_norm"
      num_attention_heads: 32
      num_layers: 16
      output_dim: 1024
      positional_embeddings: null
  
  # waiting to check
  reduce_in_full_precision: true


datasets:
  vlm_data:
    dataset_py: vlm_datasets
    dataformat: llava_json
    dataset_use: asv2_conversation_en,asv2_detailed_description_en,asv2_region_captioning_en,coco_internvl_longcap_en,coco_karpathy_train_567_en,coco_negative_gpt4o_en,coco_poetry_zh,coco_rem_en_zh,cocorem_exist_yorn_en,cocotextv2_en,cocotextv2_gpt4o_en,okvqa_en,refcoco_grounding_aug_en,refcoco_grounding_en,tallyqa_coco_en,toloka_grounding_aug_en,vqav2_en,vsr_en
    eval_dataset: aokvqa_cauldron_llava_format
    data_flatten: false
    base_interval: 2
    max_pixels: 12845056
    min_pixels: 3136
    model_max_length: 2048 
    model_type: qwen2.5vl
    per_device_batch_size: 4

  vla_data:
    dataset_py: lerobot_datasets_libero
    data_root_dir: playground/Datasets/LEROBOT_LIBERO_DATA
    data_mix: libero_goal # libero_goal
    action_type: delta_qpos # 这个没有生效
    CoT_prompt: "Your task is {instruction}. To identify the key objects for your task. Locate their bounding boxes in [x1,y1,x2,y2] format."
    CoT_answer: bbox # 写成null 就说明不启用 CoT annotation --> groot 是认为数据集有稳定定义的 --> release 版本确实应该这样假设
    default_image_resolution: [3, 224, 224] # 还没有生效
    per_device_batch_size: 16
    load_all_data_for_training: true # 考虑如何启用 eval set
    obs: ["image_0"]


trainer:
  epochs: 100
  max_train_steps: 100000
  num_warmup_steps: 5000
  save_interval: 5000
  eval_interval: 100
  learning_rate:
    base: 2.5e-05
    qwen_vl_interface: 1.0e-05
    action_model: 1.0e-04
  lr_scheduler_type: cosine_with_min_lr
  scheduler_specific_kwargs:
    min_lr: 1.0e-06
  freeze_modules: ''
  loss_scale:
    vla: 1.0
    vlm: 0.1
  max_grad_norm: 1.0
  warmup_ratio: 0.1
  weight_decay: 0.0
  logging_frequency: 10
  gradient_clipping: 1.0
  gradient_accumulation_steps: 1

  optimizer:
    name: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-08
    weight_decay: 1.0e-08

  # 待确定的参数
  is_resume: false
  resume_epoch: null
  resume_step: null
  enable_gradient_checkpointing: true
  enable_mixed_precision_training: true
