"""
InternVLA-M1 Deployment Client for Real Robot Control

This module provides the client-side interface for controlling a Franka Emika robot
using delta end-effector pose actions generated by the InternVLA-M1 model.

Communication Protocol:
- Sends: current_pose (4x4 matrix), current_gripper_width, current_joint, instruction
- Receives: target_eepose = (gripper_action, delta_eepose_6d)
  - gripper_action: -1 (open) or 1 (close)
  - delta_eepose_6d: [dx, dy, dz, droll, dpitch, dyaw]
"""

# Standard library imports
import json
import os
import time

# Third-party library imports
import numpy as np
import requests
from loguru import logger

# Local application imports
from config import deploy_config
from franka_controller import FrankaController
from tool import _6d_to_pose

# Global variables
target_eepose_log = []


def execuate():
    """Main execution function for robot control with delta EE pose."""
    np.random.seed(1)
    logger.info("=" * 60)
    logger.info("InternVLA-M1 Deployment Client Starting")
    logger.info("=" * 60)
    logger.info(f"Working directory: {os.getcwd()}")
    logger.info(f"Action type: {deploy_config.action_type}")
    logger.info(f"Inference server: {deploy_config.inference_server_url}")
    logger.info(f"Instruction: {deploy_config.language_instruction}")

    hostname = getattr(deploy_config, 'franka_hostname', "172.16.0.2")
    gripper_type = getattr(deploy_config, 'gripper_type', "robotiq")
    gripper_port = getattr(deploy_config, 'gripper_port', "/dev/ttyUSB0")
    
    logger.info(f"Robot config - Hostname: {hostname}, Gripper: {gripper_type}")
    real_robot = FrankaController(hostname=hostname, gripper_type=gripper_type, gripper_port=gripper_port)
    logger.info("Robot controller initialized")

    for i in range(3):
        real_robot.get_obs()
        time.sleep(0.1)
    logger.info("Robot warm-up complete")
    
    initial_obs = real_robot.get_obs()
    last_target_pose = initial_obs["current_pose"].copy()
    logger.info(f"Initial EE position: {last_target_pose[:3, 3]}")
    logger.info(f"Initial gripper width: {initial_obs['current_gripper_width']}")

    index_frame = 0

    try:
        while True:
            t = 0
            try:
                while True:
                    obs = real_robot.get_obs()
                    current_pose = obs["current_pose"]
                    current_gripper_width = obs["current_gripper_width"]
                    current_joint = obs["current_joint"]
                    
                    # Convert gripper width to gripper state: -1 (open) or 1 (closed)
                    current_gripper_state = -1 if current_gripper_width >= 0.04 else 1
                    
                    instruction = deploy_config.language_instruction
                    
                    payload = {
                        "data": {
                            "current_pose": current_pose.tolist(),
                            "current_gripper_state": current_gripper_state,
                            "current_joint": current_joint.tolist() if isinstance(current_joint, np.ndarray) else current_joint
                        },
                        "timestep": t,
                        "instruction": instruction,
                        "reset": True if t == 0 else False,
                    }
                    time1 = time.time()

                    target_eepose_response = requests.post(deploy_config.inference_server_url, json=payload)
                    time2 = time.time()
                    response_json = target_eepose_response.json()
                    target_eepose_data = response_json['target_eepose']
                    
                    if deploy_config.log_action_to_json:
                        log_entry = {
                            "timestep": t,
                            "target_eepose": target_eepose_data
                        }
                        if "current_subtask" in response_json:
                            log_entry["current_subtask"] = response_json["current_subtask"]
                            log_entry["high_level_instruction"] = response_json.get("high_level_instruction")
                            log_entry["is_planning_active"] = response_json.get("is_planning_active")
                        
                        target_eepose_log.append(log_entry)
                        with open("target_eepose_log.json", "w") as json_file:
                            json.dump(target_eepose_log, json_file, indent=4)

                    logger.debug(f"Inference Time: {time2 - time1:.4f}s")

                    if deploy_config.action_type == "delta_ee_pose":
                        target_gripper_action = target_eepose_data[0]
                        target_gripper_width = 0.08 if target_gripper_action >= 0 else 0.0
                        target_delta_eepose_6d = np.array(target_eepose_data[1])
                        delta_eepose_transform = _6d_to_pose(target_delta_eepose_6d)
                        new_target_pose = last_target_pose @ delta_eepose_transform
                        last_target_pose = new_target_pose
                        
                        print(f"Delta EE pose: {target_delta_eepose_6d}")
                        print(f"Gripper: {target_gripper_action} -> {target_gripper_width}")
                        action = (target_gripper_width, new_target_pose)
                        
                    elif deploy_config.action_type == "abs_ee_pose":
                        target_gripper_action = target_eepose_data[0]
                        target_gripper_width = 0.08 if target_gripper_action >= 0 else 0.0
                        target_eepose_6d = np.array(target_eepose_data[1])
                        target_eepose = _6d_to_pose(target_eepose_6d)
                        
                        print(f"Absolute EE pose: {target_eepose_6d}")
                        print(f"Gripper: {target_gripper_action} -> {target_gripper_width}")
                        action = (target_gripper_width, target_eepose)

                    real_robot.step(action, type="pose")
                    logger.info(f"[Frame {index_frame}] Gripper: {action[0]:.3f}")
                    print(f"========= Frame {index_frame} =========")
                    
                    index_frame += 1
                    t += 1
                    
            except Exception as e:
                import traceback
                traceback.print_exc()
                logger.error(f"Error at frame {index_frame}: {e}")
                
                error_obs = real_robot.get_obs()
                last_target_pose = error_obs["current_pose"].copy()
                logger.info(f"Error recovery - Target pose reset to: {last_target_pose[:3, 3]}")
    finally:
        logger.info("Deployment client shutting down")


if __name__ == "__main__":
    execuate()